### ISSUE TITLE
evaluation method

### ISSUE THREAD

**Issue by meibinbin** [biointec/jabba#1]
hello, 
    I want to know the evaluation tool that you use to evaluate your results. Please tell me if it is ok for you. Thank you very much.

**Comment by gmiclotte** [comment]
Hello,

I have attached the following files in [evaluate.zip](https://github.com/biointec/jabba/files/323275/evaluate.zip):
- generate_output.sh
- parsesam

Additionally you will need to grab the following yourself:
- get the perl script "count_fasta.pl" from https://github.com/DeWitP/SFG/tree/master/scripts
- install BLASR from https://github.com/PacificBiosciences/blasr (or some other aligner that will output to SAM format)

Mark the scripts and executables as executable. Edit lines 21-23 in generate_output.sh to point to the location of the executables (by default they are assumed to be in the current directory).

You can now run the evaluation as follows:
- when you run jabba (or another tool), use /usr/bin/time -v to obtain information concerning run time and peak memory usage.
- then run: ./generate_output.sh <some identifying string> <genome fasta> <raw reads> <corrected reads> </usr/bin/time -v output file> <file to write output to> <temp directory>
- this will produce a row for a latex table in the format specified in the generate_output.sh file

Example:
using the following parameters:
- id: Jabba_example
- genome file: genome.fasta
- raw reads: long_reads.fasta
- corrected reads: jabba-long_reads.fasta
- standard error redirected to jabba.err
- latex output written to: table
- temp directory: temp

The command line then becomes:
./generate_tools.sh Jabba_example genome.fasta long_reads.fasta jabba-long_reads.fasta jabba.err table temp

Please let me know if this works for you, or if any issues arise.

**Comment by meibinbin** [comment]
You explained it detailedly. It is very useful for me.Thank you very much.
