### ISSUE TITLE
Error: terminate called after throwing an instance of 'std::ios_base::failure'

### ISSUE THREAD

**Issue by RaverJay** [biointec/jabba#10]
Trying to correct PacBio reads with Illumina data.

Any idea why I get this error?

> time ../jabba_prost/jabba/bin/jabba -o jabba_output -k 75 -g brownie_output/DBGraph.fasta -fastq ../reads/pacbio_link/Ceury_CCMP219_New/Run25_E09/m170315_165537_42255_c100963092550000001823219507012894_s1_p0.1.subreads.fastq.gz
> FileType is fastq.
> Max Number of Threads is 48
> Graph is brownie_output/DBGraph.fasta
> DBG K is 75
> ESSA K is 1
> Max Passes is 2
> Min Seed Size is 20
> Output Directory is jabba_output
> Output Mode is short
> Reading the graph... 
> Done.
> Constructing ESSA... 
> atempting to load index jabba_output/DBGraph_1_1_1 ... 
> index loaded succesful
> Done.
> INDEX SIZE IN BYTES: 20139917
> Number of threads: 48
> Processing file 1/1: ../reads/pacbio_link/Ceury_CCMP219_New/Run25_E09/m170315_165537_42255_c100963092550000001823219507012894_s1_p0.1.subreads.fastq.gz, type: fastq.gz
> Worker threads started.
> terminate called recursively
> terminate called after throwing an instance of 'std::ios_base::failure'
> Aborted

**Comment by gmiclotte** [comment]
Hello,

looks like there's a bug in the handling of gzipped input, workaround until it is fixed would be to unzip the file. I'm sorry for the inconvenience.

Kind regards,
Giles

**Comment by RaverJay** [comment]
Alright, thanks!
