### ISSUE TITLE
apped split suffices to the read ID rather than the full header

### ISSUE THREAD

**Issue by tolot27** [biointec/jabba#13]
Currently, the suffices `_1`, `_2`, etc. are added to the header of a read rather than to its ID. Hence, the output files contain duplicate read IDs and some programs may fail on it.

I'd suggest to add the split suffices to the read ID instead.

**Comment by gmiclotte** [comment]
Hello,

thanks for the feedback.

In 02ed64e this has been changed in accordance with http://pacbiofileformats.readthedocs.io/en/5.1/FASTA.html. The suffix will now be inserted before the first whitespace in the header. This won't properly handle all fasta header formats (e.g. >db|UniqueIdentifier|EntryName), but those can be transformed in the PacBio format easily.

Kind regards,
Giles

**Comment by tolot27** [comment]
Many thanks, it works as expected.
