### ISSUE TITLE
jabba error

### ISSUE THREAD

**Issue by xinwang-bio** [biointec/jabba#2]
Hi
When I used the Jabba, It showed a error "terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
"

How to resolve it? Thank you and look forward your help.

**Comment by gmiclotte** [comment]
Hello,

this could indicate an issue with the command line arguments or with the de Bruijn graph fasta file. Could you post the command you used to call Jabba, and one fasta header of the graph file? Then I can check if these have the right format, or if some other issue is at play here.

Kind regards,
Giles Miclotte

**Comment by xinwang-bio** [comment]
maybe It is the problem of fasta format. I will try again to see wheather it will show this error. Thank you.
