### ISSUE TITLE
Core dump problem when correcting large genome

### ISSUE THREAD

**Issue by lefroyqiu** [biointec/jabba#3]
Hi, 
I use Jabba to correct a relative small genome (~400Mb), and it works very well (The DBGraph.fasta size is 415Mb, Kmer =71). However, a 'core dump' problem occurred when Jabba was used to correct a relative large genome (~1.5Gb), the size of DBGraph.fasta created by Brownie is 2.2Gb. No DBGraph_1_1_1.xxx files were created in the output directory. 
The computing server I use has 1Tb memory size and 64 cores.

The commands are as follows,
brownie graphCorrection -p brownie_DBG -k 71 illumina.fq
jabba -k 71 -g ./brownie_DBG/DBGraph.fasta -o final_Jabba -fasta filtered_subreads.fasta

Do you have any suggestions? Thank you in advance.

Jie

**Comment by gmiclotte** [comment]
Hello,

most likely the total graph sequence (+ reverse complement) is too large to be represented in the suffix array. Increasing the suffix array sparseness factor `-e --essak [default 1]` for Jabba should resolve this. With a 2.2Gb graph file, `-e 2` should suffice.

Kind regards,
Giles Miclotte
