### ISSUE TITLE
karect Segmentation fault

### ISSUE THREAD

**Issue by blsfoxfox** [biointec/jabba#4]
Hi,

I am working with 200Gb fastq file, around 100X coverage. Karect reported following error after generate a 168Gb input_file.txt.

Error Correction Started
Estimated Coverage     = 99.574112
Global Num Reads       = 908331708
Global Num Bases       = 83597028667
Global Num Kmers       = 76330375003
Global Max Read Len    = 150
Global Avg Read Len    = 92.033591
Min Overlap            = 35
Min Overlap Percentage = 0.200000
Max Overlap Error Rate = 0.250000
Truncate Factor        = 0.000000
Min Straight Edge Val  = 20.910564
Min Straight Edge Per  = 1.000000
Min Read Weight        = 0.000000
Max Mul Len Matches    = 21739130
Max Kmer Slots         = 100000
Use Qual               = 1
Match Type             = Hamming Distance
Kmer Size              = 14
Max Kmer Errors        = 2
Kmer With Errors Size  = 14
Read Index Bits        = 40
Num Threads            = 32
Memory Budget          = 274877906944[256g]
File Block Size        = 10485760[10m]
Cache Block Size       = 134217728[128m]
Max Reads Per Step     = 1000
Max Part Res           = 31
Main CorrectErrors StartFile=0
Total Reads Size = 19832824575
Building Index [0 - 19730306040]
/home/.lsbatch/1486094626.238369.shell: line 1: 10865 Segmentation fault      (core dumped) /gpfs0/home/brownie/karect/karect -correct -matchtype=hamming -celltype=diploid -memory=256 -threads=32 -inputfile=/gpfs0/home/yy/correction/bfc/yybfc_all.fastq -resultdir=/gpfs0/home/yy/assembly/jabba -tempdir=/gpfs0/home/yy/assembly/jabba

Is this related to the size of the reads file? Could you please provide some suggestions?

Thanks,

Bob

**Comment by gmiclotte** [comment]
Hello,


I seem to receive the same error when trying to run karect on a 64G RAM machine with parameter -memory=64, but I do not receive it with -memory=63. I guess karect assumes that any RAM promised through the -memory parameter is actually available to it, and so I would suggest trying to run it with a smaller memory limit.

I hope this resolves your problem.


Kind regards,
Giles
