### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by alexcorm** [biointec/jabba#5]
Hi,

I've try to correct my PacBio reads with Jabba but for every run the output file for corrected reads is empty. I am working with 1 Illumina PE library with a ~40X coverage (each file ~85Go) which was preprocessed using Trimmomatic and 1 PacBio library with 5 millions reads (~23X coverage). I've notice if I put CCS reads in the fastq, a part of those reads were corrected.

Here the command line:
`karect -correct -matchtype=hamming -celltype=diploid -memory=1024  -inputfile=${WXf1543_R1} -inputfile=${WXf1543_R2} -resultdir=karect_output -tempdir=karect_output`

`brownie graphCorrection -t 40 -e 6 -p Brownie_WXf1543_CorrGraph_k71 -k 71 ${WXf1543_R1} ${WXf1543_R2}`

`jabba -o Jabba_WXf1543_CorrGraph_k71_karect -k 71 -e 6 -g Brownie_WXf1543_CorrGraph_k71/DBGraph.fasta -fastq ${pacbio}`

Did I miss something or I've used a wrong parameter?

Thanks,
Alex

**Comment by gmiclotte** [comment]
It looks like you are using the same input for karect as for brownie. If this is indeed the case, you should instead use the output of karect as input for brownie.

Kind regards,
Giles

**Comment by alexcorm** [comment]
The variable names are the same but not the input files. 
Using trimmed reads is not a problem?

**Comment by gmiclotte** [comment]
We haven't used trimmed reads as input for karect, it is possible that this has some kind of effect, but I would expect this effect to be rather small.

I see you use -e 6 for Jabba, which might be too high. From the size and coverage of your data sets, I gather that your genome of interest contains about 2.2 Gbp? In this case it is probably better to use -e 2, assuming that the DBGraph.fasta file is not many times larger than the estimated genome size (if it is, something went wrong with the short read data preprocessing).
Increasing the sparseness factor leads to a decrease in the number of hits found. This coupled with the already quite low throughput of Jabba on large genomes, could then indeed lead to no output at all.
