### ISSUE TITLE
atempting to load index jabba_output/DBGraph_1_1_1 ...  unable to open jabba_output/DBGraph_1_1_1

### ISSUE THREAD

**Issue by yhsYhsYhs** [biointec/jabba#7]
syb@thinkstation:~/software$ ./brownie/bin/brownie graphCorrection -p brownie_output -k 75 karect_output/karect_shortreads.fasta
Welcome to Brownie v.0.1.0 (release mode)
Today is Sun Jun 25 22:21:17 2017

Entering stage 1
================
Generating kmers with k = 75 from input files...
Number of threads: 16
Processing file 1/1: karect_output/karect_shortreads.fasta, type: fasta
Number of reads processed: 28428648
Parsed input files (38s 40ms)
Total number of unique kmers in table: 11242929 (5299294 with coverage > 1)
Writing kmer file...done (531ms)
Stage 1 finished.

Entering stage 2
================
Building kmer overlap table...done (3s 339ms)
Number of kmers loaded: 5299294
Finding overlaps between kmers...
Number of threads: 16
Processing file 1/1: karect_output/karect_shortreads.fasta, type: fasta
Number of reads processed: 28428648
Done building overlap table (37s 260ms)
Overlap table contains 5299294 nodes
Extracted 127418 nodes and 237570 arcs.
Stage 2 finished.

Entering stage 3
================
Creating graph... done (127418 nodes, 237570 arcs)
Populating table... done
Number of threads: 16
Counting node and arc frequency: 
Processing file 1/1: karect_output/karect_shortreads.fasta, type: fasta
Number of reads processed: 28428648
Done counting multiplicity (35s 563ms)
Extracting graph...
Wrote 127418 nodes and 237570 arcs
Stage 3 finished.

Entering stage 4
================

 ================ Parameter Estimation ===============
Loading test graph for initial parameter estimation

 =================== Removing tips ===================
Cut-off value for removing tips is: 3
Clipped 40519/127418 nodes
Concatenated 23282 nodes

 ================== Coverage Filter ==================
Cut-off value for removing nodes: 3
Number of nodes deleted based on coverage: 10442
Concatenated 8388 nodes
Estimated Kmer coverage mean: 161.822
Estimated Kmer coverage std:  6.66718
Estimated Kmer coverage:        161.822
Estimated MKmer coverage std:   6.66718
Cut-off value:                  38.6042
Read length:                    100
Max node size to delete:        400
Red line value cov:             38.6042
Certain value cov:              11.5813
Safe value cov:                 27.023
End of parameter estimation ... 
Creating graph... done (127418 nodes, 237570 arcs)
Created graph in 0.0427182s.
Certain value: 15.4417
Safe value: 30.8834
Red line value: 42.4647

 =================== Removing tips ===================
Cut-off value for removing tips is: 42.4647
Clipped 73916/127418 nodes
Concatenated 32452 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Number of deleted nodes based on bubble detection: 106
Concatenated 172 nodes
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           
Number of deleted nodes based on bubble detection: 42
Concatenated 72 nodes

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 814
Concatenated 830 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in deleteExtraAttachedNodes: 1
Number of deleted nodes in connectSameMulNodes: 166
Concatenated 170 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in deleteExtraAttachedNodes: 1
Number of deleted nodes in connectSameMulNodes: 51
Concatenated 53 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 14
Concatenated 14 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 1
Concatenated 1 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 1
Concatenated 1 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 1
Concatenated 1 nodes
Extracting node -127418/ 98304 /127418 from graph         
Certain value: 19.3021
Safe value: 34.7438
Red line value: 46.3251

 =================== Removing tips ===================
Cut-off value for removing tips is: 46.3251
Clipped 9431/18538 nodes
Concatenated 5560 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 134
Concatenated 153 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 9
Concatenated 9 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 2
Concatenated 3 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 1
Concatenated 1 nodes
Extracting node -127418/ 98304 /127418 from graph         
Certain value: 19.3021
Safe value: 38.6042
Red line value: 50.1855

 =================== Removing tips ===================
Cut-off value for removing tips is: 50.1855
Clipped 493/3235 nodes
Concatenated 436 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in deleteExtraAttachedNodes: 1
Number of deleted nodes in connectSameMulNodes: 62
Concatenated 69 nodes
Extracting node -127418/ 98304 /127418 from graph         
Certain value: 19.3021
Safe value: 38.6042
Red line value: 54.0459

 =================== Removing tips ===================
Cut-off value for removing tips is: 54.0459
Clipped 2/2174 nodes
Concatenated 2 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in deleteExtraAttachedNodes: 1
Number of deleted nodes in connectSameMulNodes: 38
Concatenated 41 nodes
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in deleteExtraAttachedNodes: 1
Concatenated 2 nodes
Extracting node -127418/ 98304 /127418 from graph         
Certain value: 19.3021
Safe value: 38.6042
Red line value: 57.9064

 =================== Removing tips ===================
Cut-off value for removing tips is: 57.9064
Clipped 0/2087 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Number of deleted nodes in connectSameMulNodes: 27
Concatenated 27 nodes
Extracting node -127418/ 98304 /127418 from graph         
Certain value: 19.3021
Safe value: 38.6042
Red line value: 57.9064

 =================== Removing tips ===================
Cut-off value for removing tips is: 57.9064
Clipped 0/2033 nodes

 ================= Bubble Detection ==================
Extracting node -127418/ 98304 /127418 from graph           
Bubble depth: 175
Extracting node -127418/ 98304 /127418 from graph           

 ============= Delete Unreliable Nodes  ==============
Extracting node -127418/ 98304 /127418 from graph         
Graph size: 4730509 bp
Extracted 2033 nodes and 4418 arcs.
N50 is: 9897
Graph correction completed in 5.01905s.
Stage 4 finished.

Entering stage 5
================
Files produced by this stage appear to be present, skipping stage 5...

Exiting... bye!

syb@thinkstation:~/software$ ./jabba/bin/jabba -o jabba_output -k 75 -g brownie_output/DBGraph.fasta -fasta /home/sunyangbo/dataset/e.coli/longreads.fasta
FileType is fasta.
Max Number of Threads is 16
Graph is brownie_output/DBGraph.fasta
DBG K is 75
ESSA K is 1
Max Passes is 2
Min Seed Size is 20
Output Directory is jabba_output
Output Mode is short
Reading the graph... 
Done.
Constructing ESSA... 
**atempting to load index jabba_output/DBGraph_1_1_1 ... 
unable to open jabba_output/DBGraph_1_1_1**
N=9461019
N/K=9461019
M.size()=0
kmer table size: 262144
Done.
INDEX SIZE IN BYTES: 134551701
Number of threads: 16
Processing file 1/1: /home/sunyangbo/dataset/e.coli/longreads.fasta, type: fasta
Worker threads started.
Number of reads processed: 163463

**Comment by yhsYhsYhs** [comment]
work twice ,this problem disappear

**Comment by yhsYhsYhs** [comment]
syb@thinkstation:~/software$ ./jabba/bin/jabba -o jabba_output -k 75 -g brownie_output/DBGraph.fasta -fasta /home/syb/dataset/e.coli/longreads.fasta
FileType is fasta.
Max Number of Threads is 16
Graph is brownie_output/DBGraph.fasta
DBG K is 75
ESSA K is 1
Max Passes is 2
Min Seed Size is 20
Output Directory is jabba_output
Output Mode is short
Reading the graph... 
Done.
Constructing ESSA... 
atempting to load index jabba_output/DBGraph_1_1_1 ... 
index loaded succesful
Done.
INDEX SIZE IN BYTES: 134551701
Number of threads: 16
Processing file 1/1: /home/sunyangbo/dataset/e.coli/longreads.fasta, type: fasta
Worker threads started.
Number of reads processed: 163463

**But there is another problem that the result evaluated by dnadiff is error :+1: 
command:   dnadiff /home/syb/dataset/e.coli/sequence.fasta   /home/syb/software/jabba_output/Jabba-longreads.fasta** 

# CONSTRUCTIONTIME /usr/bin/mummer out.ntref 1.99
/usr/bin/mummer: cannot open file "/home/syb/software/jabba_output/Jabba-longreads.fasta" or file "/home/syb/software/jabba_output/Jabba-longreads.fasta" is empty
ERROR: mummer and/or mgaps returned non-zero

**Comment by gmiclotte** [comment]
Hello,


Jabba is unable to open the index in the first run, since it does not exist, it then constructs the index. In the next run, Jabba is able to open the index, since it exists from the previous run. There is no issue here, but I can clarify that in the terminal output.

Regarding the dnadiff issue: dnadiff says the file is empty, which would mean that Jabba was unable to correct any off the reads, this happens when the graph is too sparse or too complex.
The brownie output shows that stage 4 removes a lot of the graph, this might be too aggressive. Could you reconstruct the graph with brownie command graphConstruction instead of graphCorrection and then run Jabba on the new graph file?


Kind regards,
Giles Miclotte

**Comment by yhsYhsYhs** [comment]
syb@thinkstation:~/software$ mkdir karect_output
syb@thinkstation:~/software$ ./karect/karect -correct -matchtype=hamming -celltype=haploid -inputfile=/home/syb/dataset/e.coli/shortreads_20X.fasta -resultdir=karect_output -tempdir=karect_output
Error Correction Started
Estimated Coverage     = 6.793103
Global Num Reads       = 92002
Global Num Bases       = 9200200
Global Num Kmers       = 8464184
Global Max Read Len    = 100
Global Avg Read Len    = 100.000000
Min Overlap            = 35
Min Overlap Percentage = 0.200000
Max Overlap Error Rate = 0.250000
Truncate Factor        = 0.000000
Min Straight Edge Val  = 4.200000
Min Straight Edge Per  = 1.000000
Min Read Weight        = 0.000000
Max Mul Len Matches    = 20000000
Max Kmer Slots         = 100000
Use Qual               = 1
Match Type             = Hamming Distance
Kmer Size              = 9
Max Kmer Errors        = 2
Kmer With Errors Size  = 9
Read Index Bits        = 32
Num Threads            = 16
Memory Budget          = 10995116277760[10240g]
File Block Size        = 10485760[10m]
Cache Block Size       = 134217728[128m]
Max Reads Per Step     = 1000
Max Part Res           = 30
Main CorrectErrors StartFile=0
Total Reads Size = 18584405
Building Index [0 - 9292202]
Building Index Finished
Each following dot indicates that 1% of the required processing at current stage has been finished:
...................................................................................................
Error Correction Finished

sunyangbo@thinkstation:~/software$ mkdir brownie_output
sunyangbo@thinkstation:~/software$ ./brownie/bin/brownie graphCorrection -p brownie_output -k 75 karect_output/karect_shortreads_20X.fasta
Welcome to Brownie v.0.1.0 (release mode)
Today is Fri Jun 30 15:51:28 2017

Entering stage 1
================
Generating kmers with k = 75 from input files...
Number of threads: 16
Processing file 1/1: karect_output/karect_shortreads_20X.fasta, type: fasta
Number of reads processed: 92002
Parsed input files (300ms)
Total number of unique kmers in table: 1927825 (351645 with coverage > 1)
Writing kmer file...done (60ms)
Stage 1 finished.

Entering stage 2
================
Building kmer overlap table...done (140ms)
Number of kmers loaded: 351645
Finding overlaps between kmers...
Number of threads: 16
Processing file 1/1: karect_output/karect_shortreads_20X.fasta, type: fasta
Number of reads processed: 92002
Done building overlap table (148ms)
Overlap table contains 351645 nodes
Extracted 22291 nodes and 106 arcs.
Stage 2 finished.

Entering stage 3
================
Creating graph... done (22291 nodes, 106 arcs)
Populating table... done
Number of threads: 16
Counting node and arc frequency: 
Processing file 1/1: karect_output/karect_shortreads_20X.fasta, type: fasta
Number of reads processed: 92002
Done counting multiplicity (264ms)
Extracting graph...
Wrote 22291 nodes and 106 arcs
Stage 3 finished.

Entering stage 4
================

 ================ Parameter Estimation ===============
Loading test graph for initial parameter estimation

 =================== Removing tips ===================
Cut-off value for removing tips is: 3
Clipped 19955/22291 nodes
Concatenated 5 nodes

 ================== Coverage Filter ==================
Cut-off value for removing nodes: 3
Number of nodes deleted based on coverage: 1855
Estimated Kmer coverage mean: 5.48092
Estimated Kmer coverage std:  0.920654
Estimated Kmer coverage:        5.48092
Estimated MKmer coverage std:   0.920654
Cut-off value:                  2.68589
Read length:                    100
Max node size to delete:        400
Red line value cov:             2.68589
Certain value cov:              0.805766
Safe value cov:                 1.88012
End of parameter estimation ... 
Creating graph... done (22291 nodes, 106 arcs)
Created graph in 0.00581999s.
Certain value: 1.07435
Safe value: 2.14871
Red line value: 2.95448

 =================== Removing tips ===================
Cut-off value for removing tips is: 2.95448
Clipped 17749/22291 nodes
Concatenated 8 nodes

 ================= Bubble Detection ==================
Extracting node -22291/ 0 /22291 from graph          
Bubble depth: 175
Extracting node -22291/ 0 /22291 from graph          

 ============= Delete Unreliable Nodes  ==============
Extracting node -22291/ 0 /22291 from graph        
Certain value: 1.34294
Safe value: 2.4173
Red line value: 3.22306

 =================== Removing tips ===================
Cut-off value for removing tips is: 3.22306
Clipped 1737/4534 nodes

 ================= Bubble Detection ==================
Extracting node -22291/ 0 /22291 from graph          
Bubble depth: 175
Extracting node -22291/ 0 /22291 from graph          

 ============= Delete Unreliable Nodes  ==============
Extracting node -22291/ 0 /22291 from graph        
Certain value: 1.34294
Safe value: 2.68589
Red line value: 3.49165

 =================== Removing tips ===================
Cut-off value for removing tips is: 3.49165
Clipped 1419/2797 nodes

 ================= Bubble Detection ==================
Extracting node -22291/ 0 /22291 from graph          
Bubble depth: 175
Extracting node -22291/ 0 /22291 from graph          

 ============= Delete Unreliable Nodes  ==============
Extracting node -22291/ 0 /22291 from graph        
Certain value: 1.34294
Safe value: 2.68589
Red line value: 3.76024

 =================== Removing tips ===================
Cut-off value for removing tips is: 3.76024
Clipped 0/1378 nodes

 ================= Bubble Detection ==================
Extracting node -22291/ 0 /22291 from graph          
Bubble depth: 175
Extracting node -22291/ 0 /22291 from graph          

 ============= Delete Unreliable Nodes  ==============
Extracting node -22291/ 0 /22291 from graph        
Graph size: 148355 bp
Extracted 1378 nodes and 4 arcs.
N50 is: 102
Graph correction completed in 0.0339999s.
Stage 4 finished.

Entering stage 5
================
Files produced by this stage appear to be present, skipping stage 5...

Exiting... bye!

syb@thinkstation:~/software$ ./jabba/bin/jabba -o jabba_output -k 75 -g brownie_output/DBGraph.fasta -fastq /home/syb/dataset/e.coli/longreads.fasta
FileType is fastq.
Max Number of Threads is 16
Graph is brownie_output/DBGraph.fasta
DBG K is 75
ESSA K is 1
Max Passes is 2
Min Seed Size is 20
Output Directory is jabba_output
Output Mode is short
Reading the graph... 
Done.
Constructing ESSA... 
atempting to load index jabba_output/DBGraph_1_1_1 ... 
unable to open jabba_output/DBGraph_1_1_1
N=296711
N/K=296711
M.size()=0
kmer table size: 262144
Done.
INDEX SIZE IN BYTES: 6251389
Number of threads: 16
Processing file 1/1: /home/sunyangbo/dataset/e.coli/longreads.fasta, type: fasta
Worker threads started.
Number of reads processed: 163463
syb@thinkstation:~/software$ dnadiff /home/syb/dataset/e.coli/sequence.fasta  /home/syb/software/jabba_output/Jabba-longreads.fasta
Building alignments
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "out.ntref" of length 4641653
# construct suffix tree for sequence of length 4641653
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 46416 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /usr/bin/mummer out.ntref 1.63
# reading input file "/home/syb/software/jabba_output/Jabba-longreads.fasta" of length 1484987
# matching query-file "/home/syb/software/jabba_output/Jabba-longreads.fasta"
# against subject-file "out.ntref"
# COMPLETETIME /usr/bin/mummer out.ntref 2.83
# SPACE /usr/bin/mummer out.ntref 6.41
4: FINISHING DATA
postnuc: postnuc.cc:1427: long int revC(long int, long int): Assertion `Len - Coord + 1 > 0' failed.
Aborted (core dumped)
ERROR: postnuc returned non-zero
ERROR: Failed to run nucmer, aborting.
 I had changed dataset. But it always has run error with dnadiff.

**Comment by gmiclotte** [comment]
I have not used dnadiff before, what input does it expect? Maybe we can figure out in what way the Jabba output deviates from that. Do you have a minimal working example and minimal failing example (with Jabba output)?

**Comment by yhsYhsYhs** [comment]
dnadiff is a wapper of nucmer, it needs a reference genome and a read file in fasta or fastq format. I changed k value and finish evaluating jabba result smoothly finally. But I have a question why jabba run much faster than other correction tools, but corrected file 100X smaller than uncorrection in jabba_out folder. Is it because k value is selected unfit? This test data comes from e.coli M12 , pacBio reads is 10X genome size.

**Comment by gmiclotte** [comment]
If k is too low, then the graph will contain too many complex repeats and Jabba will not resolve them in many cases (i.e., when there is no seed in the repeats). If k is too big, then the graph will contain too many gaps, and jabba doesn't bridge gaps in the graph.
This is why we use the approach of first correcting short reads with karect, which allows us to use a rather high k value without having too many gaps.

**Comment by sybsun** [comment]
hello,
when I use Jabba to correct longreads, correct result always with too low genome coverage less than 30%. I have changed k value from shortreads length to half of shortreads length but genome coverage doesnt keep low coverage. I want to know how to select appropriate k value based on dataset?

**Comment by yhsYhsYhs** [comment]
hello,
when I use Jabba to correct longreads, correct result always with too low genome coverage less than 30%. I have changed k value from shortreads length to half of shortreads length but genome coverage  keep low coverage. I want to know how to select appropriate k value based on dataset?

**Comment by gmiclotte** [comment]
Hello,

I missed the notification for issue #9 , my apologies. I posted an answer there, and I'll close this one.

Kind regards,
Giles
