### ISSUE TITLE
cmake: command not found

### ISSUE THREAD

**Issue by supanthee** [biointec/jabba#8]
Installing brownie. When I follow the directions and use this command, the result is bash: cmake command not found.

any suggestions, please?

Thanks
$ cmake -DMAXKMERLENGTH=75 ..
-bash: cmake: command not found

**Comment by gmiclotte** [comment]
Hello,

CMake is used to build brownie and jabba, it appears that you do not have it installed, or bash can not find it in your path. You can install cmake either from your OS's repositories, or from https://cmake.org/install/ .

Kind regards,
Giles Miclotte

**Comment by supanthee** [comment]
Thank you for your response. The issue was solved.

Thank you!!
