### ISSUE TITLE
too short reads and low genome coverage after jabba corrrection 

### ISSUE THREAD

**Issue by yhsYhsYhs** [biointec/jabba#9]
Hello,I had run with following orders , and always with too short reads and low genome coverage after jabba correction . 
```
mkdir karect_output

karect -correct -matchtype=hamming -celltype=haploid -inputfile=shortreads.fasta -resultdir=karect_output -tempdir=karect_output

mkdir brownie_output

brownie graphConstruction -p brownie_output -k 75 karect_output/karect_shortreads.fasta

jabba -o jabba_output -k 75 -g brownie_output/DBGraph.fasta -fasta longreads.fasta
```
The result is showed.  Another question: How could I make the reads id not change after correction? for example: 1425_1, 1425_2… , it should be 1425 before correction.
```
>1401
TTATAAGGGTTCCTGCTTTCACAGAATTATTCCAGGGTTTATGTGTCAGGGTGGTGACTTCACACGCCATA
>1402
CCATAGATGGACTTGCCACCAGTGCCATTATGGCGTGTGAAGTCACCACCCTGA
>1415
TCAAGGTTGACAGTTGGGCAGAAGCTCTGGTTCCTCTTTAAGTGGTAATGCTTCATACCAACTTTCCCAAAGTA
>1416
AAAGTTCTGGGAAAGGGAAAGCTCCCAAAGCAGCCTGTCATCGTGAAGGCCAAATTCTTCAGCAGAAGAGCTGA
>1417
TGTCTGTTGACATAGTGATTGCTTGAAGAATCTCCCTAGAGCGAGAAAACCTCTCACACCCCAACCGGC
>1423
CATCCCACTCGGCCTGGTAACACGTGCCAGCCACCGGGGCCCTGAGCTCATACTTTTTACGGAAGGACGCC
>1425_1
CTGCCGTCTAGAAAAACCTGCCAAATATGATGACATCAAGAAGGTGGTGAA
>1425_2
CCAAAATCAAGTGGGGCGATGCTGGCGCTGAGTACGTCGTGGAGTCCACTGGCGTCTTCACCACCATGGAGAAGG
>1427
CCCCTGCCACACTCAGTCCCCCACCACACTGAATCTCCCCTCCTCACAGTT
>1430
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>1434_1
CCACACCAGTTATCCTATTGAAAGAGGGGACTGATAGCTCCCAAGGCATCCCCCAGCTTGT
>1434_2
TTTGCTGACAGGGACATGTTCTGTGCTGGCCGAGTACCTGAGGAGGATCTGAAGAGGACAATGATGGCC
>1441
CAGAAGTATGGAATAGAAAATAAATACAAATGTAGGCTATTCTGCTAATTGTTTTATAA
>1453
AACAAATACACCCATTGAAGGAAACCAGGCGGGTGATGCAGCTGCCTCTGCCAGGAGTCTACCAAATGAAGA
>1465
AGGCCCTGGTGCCCGCGCTCGCTACCAGAAATCCTACCGATAAGCCCATCGTGACTCAAAACTCACTTGTATAA
>1472_1
TGATGCACAGAGAAGGGGTTACCATGGTTTGGGACCACAGAGATCACGTCAAC

```

thank u.

**Comment by gmiclotte** [comment]
Hello,


If jabba can only correct part of the read with the primary correction, then it will attempt to create a secondary correction for the remainder of the read, that's why some reads become _1 and _2. There's no parameter to prevent this behaviour, but you could easily filter these I guess.

But those are some very short reads indeed, how long were the original reads for this sample? Are all corrected reads this short or is it mainly this sample? What read length and read coverage is there for the second generation data? What's the estimated size of the genome? If the graph is too complex, then jabba will not be able to find proper paths in it.


Kind regards,
Giles

**Comment by gmiclotte** [comment]
> hello,
when I use Jabba to correct longreads, correct result always with too low genome coverage less than 30%. I have changed k value from shortreads length to half of shortreads length but genome coverage keep low coverage. I want to know how to select appropriate k value based on dataset?

It depends wildly on your second generation data and genome. If you have, say, 30x coverage 100bp reads of a Gbp genome, then it probably won't work no matter what k-mer size you pick. Karect and brownie don't handle huge genomes well in my experience, so the resulting graph would either contain many gaps (large k) or be very dense (small k), with no good graph in between. And jabba doesn't handle a gappy or dense graph very well.

Kind regards,
Giles

**Comment by sybsun** [comment]
Only on a part of dataset. I have run jabba on genome size of 12Mbp and shortreads with 38X coverage  76bp shortreads. After I run jabba with k value 75 on my pacbio longreads, I got genome coverage 33%.  And then , I attempted jabba on a nanopore  longreads, 128X shortreads 51bp, k value 21, I got genome coverage only 2%.

**Comment by yhsYhsYhs** [comment]
Only on a part of dataset. I have run jabba on genome size of 12Mbp and shortreads with 38X coverage 76bp shortreads. After I run jabba with k value 75 on my pacbio longreads, I got genome coverage 33%. And then , I attempted jabba on a nanopore longreads, genome size 5M, 128X shortreads 51bp, k value 21, I got genome coverage only 2%.

**Comment by gmiclotte** [comment]
Jabba probably won't work with extremely short reads, and k should be significantly smaller than the read length, else the graph will be very disconnected.

Kind regards,
Giles Miclotte
